package com.assessment.kevinw.pitgame.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Pit {

    // Custom constructor because id is autogenerated
    public Pit(int pitId, int amountOfStonesInPit) {
        this.pitId = pitId;
        this.amountOfStonesInPit = amountOfStonesInPit;
    }

    @Id
    @GeneratedValue
    private Long id;

    private int pitId;

    private int amountOfStonesInPit;
}
